### ISSUE TITLE
Iteration Plan for 2025-01 #5

### ISSUE THREAD

**Issue by crazygo** [askman-dev/askman-chrome-extension#140]
*This issue was created by a bot. Please do not modify it directly.*

Iteration Plan for milestone: 2025-01

- [x] [Use regular expressions to establish page blacklist rules](https://github.com/askman-dev/askman-chrome-extension/issues/112)
- [x] [Shortcuts for frame](https://github.com/askman-dev/askman-chrome-extension/issues/128)
- [x] [Use command + click to send framework selection quickly](https://github.com/askman-dev/askman-chrome-extension/issues/129)
- [x] [Copy response and code blocks](https://github.com/askman-dev/askman-chrome-extension/issues/136)
- [ ] [Iteration Plan for 2025-01 #5](https://github.com/askman-dev/askman-chrome-extension/issues/140)
- [x] [Windows Compatibility](https://github.com/askman-dev/askman-chrome-extension/issues/142)
- [x] [Hide the Ask button on the page by default](https://github.com/askman-dev/askman-chrome-extension/issues/144)
- [x] [Release/0.0.5](https://github.com/askman-dev/askman-chrome-extension/pull/149)
- [x] [Dev 0.0.6](https://github.com/askman-dev/askman-chrome-extension/pull/150)
- [x] [chore(deps): bump cross-spawn from 6.0.5 to 6.0.6](https://github.com/askman-dev/askman-chrome-extension/pull/151)
- [x] [chore(deps-dev): bump @commitlint/cli from 18.4.4 to 19.6.1](https://github.com/askman-dev/askman-chrome-extension/pull/152)
- [x] [chore(deps-dev): bump prettier from 3.1.0 to 3.4.2](https://github.com/askman-dev/askman-chrome-extension/pull/153)
- [x] [chore(deps-dev): bump eslint from 9.14.0 to 9.18.0](https://github.com/askman-dev/askman-chrome-extension/pull/154)
- [x] [Dev 0.0.8](https://github.com/askman-dev/askman-chrome-extension/pull/156)
- [x] [Support for Managing Multiple System Prompts](https://github.com/askman-dev/askman-chrome-extension/issues/157)
- [x] [feat: Add Prompt Template Selector for Structured Thinking Frameworks](https://github.com/askman-dev/askman-chrome-extension/issues/161)
- [x] [feat: Make dropdown selections temporary when using command+enter/click](https://github.com/askman-dev/askman-chrome-extension/issues/162)
- [x] [Dev 0.0.11](https://github.com/askman-dev/askman-chrome-extension/pull/163)
- [x] [fix(options): adjust WeChat QR code display width for better visibility](https://github.com/askman-dev/askman-chrome-extension/pull/164)
- [x] [Add "New Conversation" Feature for Page Reading Context](https://github.com/askman-dev/askman-chrome-extension/issues/171)
- [x] [Dev 0.0.13](https://github.com/askman-dev/askman-chrome-extension/pull/173)
- [x] [chore(docs): update documentation link in external configuration](https://github.com/askman-dev/askman-chrome-extension/pull/175)
- [x] [Dev 0.0.15](https://github.com/askman-dev/askman-chrome-extension/pull/176)
