### ISSUE TITLE
epic: V0.1.0 版本计划

### ISSUE THREAD

**Issue by crazygo** [askman-dev/askman-chrome-extension#8]
这是第一个可以请朋友测试的MVP版本，最重要的目标是：

* 需要具备流畅的页面内对话的体验
* 需要针对2个开发者常去的网站进行对话上下文定制，并且通过上下文的设计，可以得到更高质量的回复。

## TODO

- [X] 右键菜单、browser action图标、文案未定
- [X] 背景资料以 json 格式写入到 prompt 中，对回答效果的影响待测试
- [X] 产品名字未定
- [X] 需要给客户端分配一个固定、长期的 jwt，方便以后更换
- [X] **问那个人** 得改个名，这不像个产品😓

### 系统设计

- [X] 交互设计 [https://www.figma.com/file/MxfYG7rd1csvZaU6BaZaTd/AskMan---extensions?type=design&node-id=269-854&mode=dev](https://www.figma.com/file/MxfYG7rd1csvZaU6BaZaTd/AskMan---extensions?type=design&node-id=269-854&mode=dev)
- [X] 与 Prompt 设计 [https://github.com/askman-dev/askman-chrome-extension/issues/13](https://github.com/askman-dev/askman-chrome-extension/issues/13)

### 页面内浮窗

- [X] [https://github.com/askman-dev/askman-chrome-extension/issues/9](https://github.com/askman-dev/askman-chrome-extension/issues/9) @crazygo
- [X] 

  [GitHub: Let’s build from here](https://github.com/askman-dev/askman-chrome-extension/issues/7)

   @Ed4ward

### 对话工具

- [X] 鼠标 hover 【工具】就会显示下拉菜单。这个版本中支持的工具项见 [https://github.com/askman-dev/askman-chrome-extension/issues/22](https://github.com/askman-dev/askman-chrome-extension/issues/22)
- [ ] ~~输入框激活时，使用 Tab 可以移动到 【工具】，同时自动打开菜单。使用⬆️⬇️回车操作可以使用某一个工具~~

### 对话上下文

- [X] 打开浮窗时，自动引用页面选中的文本 [https://github.com/askman-dev/askman-chrome-extension/issues/10](https://github.com/askman-dev/askman-chrome-extension/issues/10)
- [X] 打开浮窗时，自动引用页面标题 [https://github.com/askman-dev/askman-chrome-extension/issues/23](https://github.com/askman-dev/askman-chrome-extension/issues/23)

### 设置页面

- [ ] [~~https://github.com/askman-dev/askman-chrome-extension/issues/29~~](https://github.com/askman-dev/askman-chrome-extension/issues/29)~~ @crazygo~~
