### ISSUE TITLE
Iteration Plan for 2024-11 #8

### ISSUE THREAD

**Issue by crazygo** [askman-dev/askman-chrome-extension#88]
*This issue was created by a bot. Please do not modify it directly.*

Iteration Plan for milestone: 2024-11

- [x] [Chrome 商店描述](https://github.com/askman-dev/askman-chrome-extension/issues/74)
- [x] [设计工具模板逻辑](https://github.com/askman-dev/askman-chrome-extension/issues/75)
- [x] [支持配置 3 个自定义模型，并在对话时切换模型进行提问](https://github.com/askman-dev/askman-chrome-extension/issues/76)
- [x] [合并工具消息和引用消息的拼接格式](https://github.com/askman-dev/askman-chrome-extension/issues/77)
- [x] [在飞书文档中屏蔽 ask 按钮](https://github.com/askman-dev/askman-chrome-extension/issues/78)
- [x] [Iteration Plan for 2024-11](https://github.com/askman-dev/askman-chrome-extension/issues/87)
- [x] [Iteration Plan for 2024-11 #8](https://github.com/askman-dev/askman-chrome-extension/issues/88)
- [x] [Internationalization - Set English as Default Language](https://github.com/askman-dev/askman-chrome-extension/issues/89)
- [x] [Create a product logo](https://github.com/askman-dev/askman-chrome-extension/issues/90)
- [x] [Clicking the action icon triggers an in-page chat popup](https://github.com/askman-dev/askman-chrome-extension/issues/91)
- [x] [After sending the message, keep the Tool selected to facilitate continuous use of the same tool.](https://github.com/askman-dev/askman-chrome-extension/issues/92)
- [x] [feat(chat): keep the tools state after sending the message](https://github.com/askman-dev/askman-chrome-extension/pull/93)
- [x] [chore(deps-dev): bump @types/node from 20.8.10 to 22.8.6](https://github.com/askman-dev/askman-chrome-extension/pull/94)
- [x] [chore(deps-dev): bump eslint from 8.56.0 to 9.14.0](https://github.com/askman-dev/askman-chrome-extension/pull/95)
- [x] [chore(deps-dev): bump eslint-plugin-prettier from 5.0.1 to 5.2.1](https://github.com/askman-dev/askman-chrome-extension/pull/96)
- [x] [feat(ask): update icons and manifest for extension](https://github.com/askman-dev/askman-chrome-extension/pull/97)
- [x] [update icons](https://github.com/askman-dev/askman-chrome-extension/pull/98)
- [x] [Allow the use of @ to input page variables in the input box](https://github.com/askman-dev/askman-chrome-extension/issues/102)
- [x] [Display toml on menu](https://github.com/askman-dev/askman-chrome-extension/pull/103)
- [x] [Use @ to mention contens](https://github.com/askman-dev/askman-chrome-extension/pull/104)
- [x] [Render the list of references used in the page context according to the framework.](https://github.com/askman-dev/askman-chrome-extension/issues/111)
- [x] [feat(ask): simplify logo, enhance URL support, update UI/UX](https://github.com/askman-dev/askman-chrome-extension/pull/113)
- [x] [Display API Providers in Model List to Thank Platform Support](https://github.com/askman-dev/askman-chrome-extension/issues/116)
- [x] [Display the settings button in the popup](https://github.com/askman-dev/askman-chrome-extension/issues/124)
- [x] [Release/0.0.3](https://github.com/askman-dev/askman-chrome-extension/pull/125)
- [x] [Dessert: Hover to open the frame menu...](https://github.com/askman-dev/askman-chrome-extension/issues/127)
